<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="10000">
      <img src="https://cdn.pixabay.com/photo/2016/11/23/17/25/woman-1853939_960_720.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <img src="https://cdn.pixabay.com/photo/2016/08/01/20/13/girl-1561989_960_720.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://cdn.pixabay.com/photo/2015/03/21/14/34/silhouette-683751_960_720.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<div class="container-fluid text-center">
    <div class="row">
        <h2>Como Funciona </h2>
    </div>
    <div class="row">
        <div class="col-lg-3">
            <img src="https://img.icons8.com/?size=512&id=39210&format=png"/>
            <p>Navegue pelo site</p>
        </div>
        <div class="col-lg-3">
            <img src="https://img.icons8.com/?size=512&id=15873&format=png"/>
            <p>Monte seu combo</p>
        </div>
        <div class="col-lg-3">
            <img src="https://img.icons8.com/?size=512&id=86719&format=png"/>
            <p>Escolha a forma de entrega</p>
        </div>
        <div class="col-lg-3">
            <img src="https://img.icons8.com/?size=512&id=215&format=png"/>
            <p>E a forma de Pagamento</p>
        </div>
    </div>
</div>



<?php
//Get Object Manager Instance
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productCollectionFactory = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
$categoryCollectionFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
$categoryId = '2'; // ID da Categoria
$category = $categoryCollectionFactory->create()->load($categoryId);
 
$collection = $productCollectionFactory->create();
$collection->addAttributeToSelect('*');
$collection->addCategoryFilter($category);
$collection->addAttributeToFilter('visibility', \Magento\Catalog\Model\Product\Visibility::VISIBILITY_BOTH); //se o produto é visível individualmente
$collection->addAttributeToFilter('status',\Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED); //somente produtos habilitados
 ?>

<div class="slider">
	<div class="slide-track">
        <?php
        foreach($collection as $product){ ?>
		<div class="slide text-center">
            <a href="<?= $block->getBaseUrl() . $product['url_key']; ?>.html">
			    <img src="http://m245p1.com/media/catalog/product/<?= $product['small_image']; ?>" height="100" width="250" alt="" />
                <p class="name-product"><?= $product['name']; ?></p>
                <p class="name-product price-product">$ <?= $product['price']; ?></p>
            </a>
        </div>
        <?php } ?>
        <?php foreach($collection as $product){ ?>
		<div class="slide text-center">
            <a href="<?= $block->getBaseUrl() . $product['url_key']; ?>.html">
			    <img src="http://m245p1.com/media/catalog/product/<?= $product['small_image']; ?>" height="100" width="250" alt="" />
                <p class="name-product"><?= $product['name']; ?></p>
                <p class="name-product price-product">$ <?= $product['price']; ?></p>
            </a>
        </div>
        <?php } ?>
	</div>
</div>

<div class="container-fluid text-center banner-grid">
    <div class="row">
        <div class="col-lg-2 col-md-4 col-sm-12">
            <a href="<?= $block->getBaseUrl(); ?>">
                <img src="https://cdn.pixabay.com/photo/2019/08/02/23/09/man-4380804_960_720.jpg"/>
            </a>
        </div>
        <div class="col-lg-2 col-md-4 col-sm-12">
            <a href="<?= $block->getBaseUrl(); ?>">
                <img src="https://cdn.pixabay.com/photo/2016/03/27/23/08/woman-1284656_960_720.jpg"/>
            </a>
        </div>
        <div class="col-lg-2 col-md-4 col-sm-12">
            <a href="<?= $block->getBaseUrl(); ?>">
                <img src="https://cdn.pixabay.com/photo/2021/11/02/19/32/basketball-6763978_960_720.jpg"/>
            </a>
        </div>
        <div class="col-lg-2 col-md-4 col-sm-12">
            <a href="<?= $block->getBaseUrl(); ?>">
                <img src="https://cdn.pixabay.com/photo/2023/03/05/23/46/girl-7832382_960_720.jpg"/>
            </a>
        </div>
        <div class="col-lg-2 col-md-4 col-sm-12">
            <a href="<?= $block->getBaseUrl(); ?>">
                <img src="https://cdn.pixabay.com/photo/2020/03/11/17/32/engineer-4922781_960_720.jpg"/>
            </a>
        </div>
    </div>
</div>
<script>
    jQuery('.carousel').carousel({
  interval: 2000
})
</script>